### ISSUE TITLE
Autoformatting changes quotes and removes trailing commas

### ISSUE THREAD

**Issue by harmeetjaipur** [jonlabelle/SublimeJsPrettier#105]
Hi,

I have been using JsPrettier for a while now and I haven't change any settings. But today the autoformatting is changing all single quotes to double and removes the trailing commas.

Options: 

> {
    "printWidth": 80,
    "singleQuote": true,
    "trailingComma": "all",
    "bracketSpacing": true,
    "jsxBracketSameLine": true,
    "parser": "babylon",
    "semi": true,
    "requirePragma": false,
    "proseWrap": "true"
  }

Version: 1.8.2

Before: 

> export function fetchAllAgreements() {
  return fetch('/agreements', {
    method: 'GET',
    credentials,
  }).then(res => res.json());
}

> export function fetchAllBuildingBlocks() {
  return fetch('/buildingblocks', {
    method: 'GET',
    credentials,
  }).then(res => res.json());
}

> export function fetchAllSubcategories() {
  return fetch('/subcategories', {
    method: 'GET',
    credentials,
  }).then(res => res.json());
}

After formatting on file save:

> export function fetchAllAgreements() {
  return fetch("/agreements", {
    method: "GET",
    credentials
  }).then(res => res.json());
}

> export function fetchAllBuildingBlocks() {
  return fetch("/buildingblocks", {
    method: "GET",
    credentials
  }).then(res => res.json());
}

> export function fetchAllSubcategories() {
  return fetch("/subcategories", {
    method: "GET",
    credentials
  }).then(res => res.json());
}

This is causing formatting issues across all JS files for my project and ESLint is throwing errors as well. How can I prevent this from happening?

**Comment by samkessaram** [comment]
Oddly, the same thing started happening with me today as well, with the addition of ignoring my `"semi": false` setting. I tried uninstalling and reinstalling both Prettier and the SublimeJsPrettier, but my settings still aren't being used.

**Comment by harmeetjaipur** [comment]
It is puzzling and I have been looking into this but cant seem to boil down the issue.

**Comment by mandx** [comment]
As a workaround for the time being, I copied the object under the `prettier_options` key in my JsPrettier User settings, and pasted it under the `"prettier"` key in the `package.json` file of my project. For example:
```json
{
  "name": "...",
  "dependencies": {
    "...": "..."
  },
  "prettier": {
    "printWidth": 100,
    "singleQuote": true,
    "trailingComma": "all",
    "bracketSpacing": true,
    "jsxBracketSameLine": true,
    "parser": "flow",
    "semi": true,
    "requirePragma": false
  }
}
```

**Comment by serhiipalash** [comment]
I have the same bug today.

**Comment by serhiipalash** [comment]
> pasted it under the "prettier" key in the package.json

Works! Thanks @mandx

**Comment by harmeetjaipur** [comment]
> {
  "name": "...",
  "dependencies": {
    "...": "..."
  },
  "prettier": {
    "printWidth": 100,
    "singleQuote": true,
    "trailingComma": "all",
    "bracketSpacing": true,
    "jsxBracketSameLine": true,
    "parser": "flow",
    "semi": true,
    "requirePragma": false
  }
}

The autoformatting stops for me as soon as I  do this.

**Comment by mandx** [comment]
@harmeetjaipur are you copying the whole snippet? Or just the object under the `"prettier"` key?

**Comment by planetcohen** [comment]
Same issue for me

**Comment by harmeetjaipur** [comment]
I was trying to fix this issue since past few hours and some setting(s) on my end must have messed up. I restored my system to 11 AM today and then added the "prettier" object as suggested by @mandx and it is working as it was now. Thanks @mandx.

**Comment by TimothyDLewis** [comment]
I came across a similar issue with my setup, this time involving the `printWidth` setting. I tried setting `printWidth` to something higher than 80 (wide-screen development environment) and no matter where I changed that setting, it was overridden and formatting at the default 80 character breakpoint.

@mandx 's solution of adding to `package.json` worked, but this isn't a solo project, and I didn't want to have to worry about that setting being committed/replaced/etc. (Not a security/vulnerability issue, just preference). So, to solve this, I added a file called `.prettierrc.json` in my `~` directory, and added these settings:

```
{
	"printWidth": 500,
	"singleQuote": false,
	"trailingComma": "none",
	"bracketSpacing": true,
	"jsxBracketSameLine": false,
	"parser": "babylon",
	"semi": true,
	"requirePragma": false,
	"proseWrap": "preserve",
	"arrowParens": "avoid"
}
```
Next in Sublime, I edited `Preferences -> Settings -> Packages -> JsPrettier -> User` to include this addition to the CLI argument:

```
...
"additional_cli_args": {
	"--config": "<path/to/.prettierrc.json>" // Override to valid path
},
...
```

Following these simple changes, the next time I ran the `js_prettier` command via Sublime everything worked as expected.

Versions: 

- JsPrettier: 1.20.0 (2018-02-13)
- Prettier: version 1.10.2 (prev. 1.7.4 <sup>1</sup>)

<sup>1</sup> Note: I had to upgrade my prettier version. I had to do this via uninstall and install since `update` didn't seem to want to work (`npm uninstall -g prettier`, `npm install -g prettier`).

**Comment by coreylight** [comment]
Same issue. I do not install prettier globally as I like to use the repository in question's local prettier for a clean upgrade path (just say no to global modules). I only use the jsPrettier user settings in sublime. Adding prettier settings to the package.json is not the solution that will work for us, as we hook into prettier with eslint in a different fashion. The most recent update has broken the current functionality for me and my team. Hopefully we can find the root cause together!

**Comment by andrew-culver** [comment]
We lost our `"semi": false` and `"trailingComa": "es5"` today, and it did not matter if they were set in `Settings - Default` or `Settings - User.
`

But this worked as a work-around:

```
	"additional_cli_args": {
		"--trailing-comma": "es5",
		"--no-semi": "" 
	},

```

**Comment by pljeskavica** [comment]
This happened today to me as well, just like @andrew-culver said adding:
```
"additional_cli_args": {
    "--trailing-comma": "all",
    "--single-quote": true
  },
```
to `Settings - User` worked for now and did not alter a git tracked file like package.json

**Comment by planetcohen** [comment]
Seriously, you closed this issue? We found workarounds, but the code is still broken.

**Comment by jonlabelle** [comment]
@planetcohen Correct. The [issue template](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/.github/ISSUE_TEMPLATE.md#generated-prettier-command-line-arguments) wasn't followed, in particular the [generated command-line args](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/.github/ISSUE_TEMPLATE.md#generated-prettier-command-line-arguments) step. If it was, I could offer suggestions, or troubleshoot the plug-in.
