### ISSUE TITLE
Crashed in sublime Text 3

### ISSUE THREAD

**Issue by nvrdawn** [jonlabelle/SublimeJsPrettier#114]
JsPrettier/JsPrettier.py 
line 245

prettier_cli_path = resolve_prettier_cli_path(view, PLUGIN_PATH, st_project_path)

Why does this function need arguement st_project_path?
Jsprettier would not work properly due to this line on sublime text 3 in the project that does not contain prettier package.

Is this necessary?
I can't find the option that can abandon this arg.

**Comment by jonlabelle** [comment]
It's necessary if Prettier is installed relative to your project path. The logic has always [been there](https://github.com/jonlabelle/SublimeJsPrettier/commit/c1b5eb304060ece13b1b3a7440bfe9494b2bfee5). However, the project path is now passed in as parameter - and since the project path is already discovered at the time `resolve_prettier_cli_path` runs.

For whatever reason - after the update was pushed, the plug-in wasn't reloading properly (for some people). Only uninstalling/reinstalling the plug-in in Package Control corrected the problem.

Though I'm not sure why you would want to *...abandon this arg*... you can for go prettier cli path resolution by simply setting the (absolute) path to prettier in your [`prettier_cli_path`](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L50) setting.
