### ISSUE TITLE
File scrolling up after saving

### ISSUE THREAD

**Issue by ivanbanov** [jonlabelle/SublimeJsPrettier#161]
After saving a file, if prettier needs to fix anything on it the file will scroll-up 1 line, and it repeats for every `cmd+s`

![prettier](https://user-images.githubusercontent.com/2953018/52405556-d910df00-2acb-11e9-9c1c-cf5ac6edcb1a.gif)

**Prettier version** 
1.16.1

**JsPrettier Plug-in Version**
1.24.7

**Platform**
macOS 10.14.2
Sublime Build 3176

**JsPrettier.sublime-settings**
```json
{
  "auto_format_on_save": true,
  "auto_format_on_save_requires_prettier_config": true,
  "auto_format_on_save_excludes": [
    "*/node_modules/*",
    "*.json",
  ],
  "prettier_cli_path": "/usr/local/bin/prettier"
}
```

**Steps to reproduce the behavior**
Just save a file 😅

**Comment by notiv-nt** [comment]
And....

code folding

![image](https://user-images.githubusercontent.com/10743009/52473404-c15a5900-2ba6-11e9-966d-292fc01807ad.png)

**Comment by jonlabelle** [comment]
Yes, this can definitely be improved/fixed.

**Comment by kylebebak** [comment]
Nothing productive to add, just wanted to say I love this plugin =)

**Comment by jonlabelle** [comment]
So there's nothing in the plug-in that would cause the view's position to move like this - via API or otherwise. But it's definitely happening, and reproducible. You'll notice, the line number stays the same, and the contents above and below the formatted line don't change.

Could be an issue w/ the editor, I really don't know at this point. But unfortunately, there's not much I can do for this one. :(
