### ISSUE TITLE
 Removes new line at EOF when file has been reformatted

### ISSUE THREAD

**Issue by greggb** [jonlabelle/SublimeJsPrettier#17]
Looks like the `trim_trailing_line_breaks` is also removing the newline at EOF. I had originally filed an issue on the main Prettier repo https://github.com/jlongster/prettier/issues/708 but ended up tracking it down to that function.

I noticed a few commits around removing line breaks, so I'm not quite sure what the solution would be for leaving the EOF new line.

I attempted to change `\Z` to `\z` which seemed to work, but not sure what the fallout is for the other line breaks you were seeing.

**Comment by sentience** [comment]
I’m seeing this too. I thought it had been resolved in #13, but it turns out the end-of-file line break stays as long as JsPrettier doesn’t make changes to the file. If I change the formatting and then JsPrettier fixes it on save, the end-of-file line break disappears at the same time.

**Comment by jonlabelle** [comment]
[Here's](https://github.com/jonlabelle/SublimeJsPrettier/issues/13#issuecomment-279122053) why...

**Comment by sentience** [comment]
@jonlabelle The discussion there is pretty fragmented so I'm having trouble following it. If I understand right you're saying that this bug is because Prettier is designed to format whole files but this package is trying to use it to format selected fragments, which means you have to do a bunch of work to remove the end-of-file/selection newlines that Prettier is inserting, and that's impossible for you to do without also removing the newline at the end of the file whenever Prettier makes a change.

This, to me, is further reason to ditch the “format selection” feature of this package. Prettier is designed to format whole files and that is going to be what the overwhelming majority of people want to use it for, so why try to make it format selections and incur the bugs that mismatch brings?

Formatting arbitrary JavaScript fragments seems to me like it's always going to be fragile at best, fatally flawed at worst. For example, an arbitrary selection may contain incomplete syntax structures, such as when you select and try to format just the first half of a function declaration; in many such cases, I can't imagine Prettier would be able to do anything useful.

If you feel strongly about preserving the selection formatting, @jonlabelle, perhaps the right thing is for those of us who only want reliable full-file formatting to fork this package so that both options are available?

**Comment by sentience** [comment]
By the way, I have `ensure_newline_at_eof_on_save` enabled and I'm still seeing this.

**Comment by jonlabelle** [comment]
@sentience: I couldn't agree with you more. And I'm beginning to regret including the format *selection(s)* feature all together.

**Comment by jonlabelle** [comment]
And [this enhancement](https://github.com/jonlabelle/SublimeJsPrettier/commit/333ae0584acf339322675967271ec97e084c9d52) has been published.

**Comment by greggb** [comment]
Thanks for looking into this. Working great now.
