### ISSUE TITLE
Disable settings mapping when prettier_config_exists

### ISSUE THREAD

**Issue by alanhoff** [jonlabelle/SublimeJsPrettier#173]
IMHO the plugin should ignore merging `JsPrettier.sublime-settings` into [`prettier_options`][1] when `prettier_config_exists`, avoiding unexpected behavior.

This plugin wont work out of the box with older JsPrettier versions and it's very annoying for me since I work with multiple projects thus multiple JsPrettier versions. The solution I found was to delete the [config mapping][2] altogether whenever this plugin updates so it wont keep forcing configs that I never set, like `parser`.

[1]: https://github.com/jonlabelle/SublimeJsPrettier/blob/2285eaafac651ed70b7b152bfb2206909c48dc27/JsPrettier.py#L495
[2]: https://github.com/jonlabelle/SublimeJsPrettier/blob/2285eaafac651ed70b7b152bfb2206909c48dc27/JsPrettier.py#L520-L626

**Comment by jonlabelle** [comment]
@alanhoff: just set your Prettier [config precedence](https://prettier.io/docs/en/cli.html#config-precedence) preference to `file-override` in [additional cli args](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L236).

Example JsPrettier.sublime-settings > **additional_cli_args**:

```json
{
    "additional_cli_args": {
        "--config-precedence": "file-override"
    }
}
```

**Comment by alanhoff** [comment]
@jonlabelle  this indeed solves some of the problems but it still forces a `parser` since I do not specify one inside `.prettierrc` but this plugin does.

I appreciate your reply anyways.

**Comment by markalfred** [comment]
@alanhoff @jonlabelle It seems like Prettier [automatically infers the parser](https://prettier.io/docs/en/options.html#parser) based on the input file now. In the past I don't think this was true, but now since Prettier handles this, does that make all of the code in this block redundant?

https://github.com/jonlabelle/SublimeJsPrettier/blob/2285eaafac651ed70b7b152bfb2206909c48dc27/JsPrettier.py#L526
