### ISSUE TITLE
env: node: No such file or directory

### ISSUE THREAD

**Issue by jt3k** [jonlabelle/SublimeJsPrettier#189]
doesnt work

0) install new macOS and SublimeText
1) install prettier plugin in SublimeText
2) yarn global add prettier
3) open context menu and choose "JsPrettier Format Code"
```
------------------
 JsPrettier ERROR 
------------------

Prettier reported the following output:

env: node: No such file or directory
```

This is a serious problem that appears every time you install the plugin on every new computer

**Comment by jonlabelle** [comment]
Though you didn't fill out the required [issue template](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), sounds like the paths to either Prettier and or Node can't be discovered... probably because they're in a non-standard location.

Just add the paths to your JsPrettier settings file, [here](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L61) and [here](https://github.com/jonlabelle/SublimeJsPrettier/blob/master/JsPrettier.sublime-settings#L90), accordingly.

**Comment by jt3k** [comment]
@jonlabelle, hmm... maybe you can try to find these paths inside the plugin using the `which node` and `which prettier` console commands?

**Comment by jonlabelle** [comment]
See [solution](https://github.com/jonlabelle/SublimeJsPrettier/issues/255#issuecomment-1152839965).
