### ISSUE TITLE
Does not work on Sublime Version 4

### ISSUE THREAD

**Issue by nikitavoloboev** [jonlabelle/SublimeJsPrettier#223]
- [Prettier doesn't run when saving the files after upgrading to version 4 ] **Explain the Issue and Expected Behavior**
- [2.0.5] **Prettier version**
- [1.30.7] **JsPrettier Plug-in Version**
- [macOS version 10.15.6] **Platform Details**
- [no it is not, works correctlyf] **Is the same behavior observed when run against Prettier directly?**
- **The contents of your** `User/JsPrettier.sublime-settings` **file**

```
{
  "auto_format_on_save": true,
  "auto_format_on_save_excludes": [
    "*/node_modules/*",
  ],
  "prettier_cli_path": "/usr/local/bin/prettier",
}
```

Running Sublime Text 4 Dev Build 4079.

**Comment by nikitavoloboev** [comment]
If you can test it on 4, it would be amazing @jonlabelle  

You can get latest dev build on [SublimeHQ Discord Server](https://discord.gg/D43Pecu) in #announcments

**Comment by nikitavoloboev** [comment]
Strange, I quit the app and it started working again. Maybe something happened in background.

**Comment by delroh** [comment]
Similar thing happened to me but using sublime text 3.2.2 build 3211. Something failed while sublime was starting up, I ignored it and then when I wanted to run the jsPrettier command through ctrl+shift+p, it was not there. So I start checking, open up sublime terminal and saw that this and another package where added to an ignore packages array.  Restarting sublime fixed it and format command appears again on ctrl+shift+p. This might be a sublime text issue when loading packages. Thought it was worth mentioning since very similar thing happened to me.
