### ISSUE TITLE
Error --no-config with JsPrettier in Sublime Text 3

### ISSUE THREAD

**Issue by pmdownie** [jonlabelle/SublimeJsPrettier#63]
Hi there.
Have updated JsPrettier and am getting this error in my Sublime Console when I try and save a file:

------------------
 JsPrettier ERROR 
------------------

Prettier reported the following error:

Ignored unknown option: --no-config

Process finished with exit code 0

------------

Wen I try the prettier CLI from the command line it works fine for a selected file.

Version of prettier: 1.5.2
JsPrettier Plug-in Version: 1.14.2
Platform: Sublime Text 3

**Comment by RaghavendhraK** [comment]
:+1:

**Comment by jonlabelle** [comment]
You're running an outdated version of Prettier. Please update again to the latest version (v1.6.1).

**Comment by glennr** [comment]
I've also run into this issue (we are running prettier v1.5 on purpose because we are not ready to upgrade all our JSX files :-)

@jonlabelle - while upgrading prettier might fix the problem, it seems strange to me that this codepath is being evaluated at all. 

The `--no-config` stuff is inside the ` if not prettier_config_exists:` block in https://github.com/jonlabelle/SublimeJsPrettier/blob/38d682a25bfa4726a79918be30dfe247ef4b627c/JsPrettier.py

But this isnt new logic - the --no-config codepath has been there for ages, and our prettier config hasnt changed, so why is this package breaking now?

**Comment by glennr** [comment]
Ok - just needed to RTFM. Saw the changelog for v1.14 requires prettier 1.6.

For all those with the same issue, you'll need to install SublimeJsPrettier manually, and check out `tags/1.13.2` to use it with prettier v1.5

**Comment by alyoness** [comment]
I am getting the same error as @pmdownie. 

I am using:
- SublimeText 3
- Prettier v1.6.1 (also fails when I revert to v1.5.3)
- JSPrettier v1.15.6

**Comment by lucasjans** [comment]
I resolved this by downgrading JsPrettier and reverting to an older Prettier. And disabling auto_upgrade for Sublime packages.

**Comment by revolunet** [comment]
resolved with `npm i -g prettier@latest`

**Comment by jonlabelle** [comment]
You guys just need to update your prettier version to the latest (which today is, v1.6.1).

Per @revolunet, just do a:

```
npm i -g prettier@latest
```
